# title: Steven Swanbeck
# logo: /assets/img/headshot.jpeg
# description: Robotics Engineer
# show_downloads: false
# theme: jekyll-theme-minimal

# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: hydecorp/hydejack
remote_theme: alshedivat/al-folio
# remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Steven Swanbeck
logo: /assets/img/headshot-modified.png
description: "Robotics Graduate Student, Researcher, and Engineer \n [LinkedIn](https://www.linkedin.com/in/stevenswanbeck/) \n [GitHub](https://github.com/steven-swanbeck)"
show_downloads: false
